config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  resources :feedback
  root 'feedback#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    extend Mobility
    translates :name, type: :string
    translates :email, type: :string
    translates :role, type: :string
    translates :feedback, type: :text
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Setting the intertionalization for which is refered to values of application.rb in config
    
  before_action :set_locale

  private

  def default_url_options
    { locale: I18n.locale}
  end

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
    Mobility.locale = extract_locale|| I18n.default_locale
  end

  def extract_locale(attr = :locale)
    parsed_locale = params[attr]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale.to_sym : nil
  end
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
    before_action :set_user_feedback, only: %i[ show edit update destroy ]

  # GET /user_feedbacks or /user_feedbacks.json
  def index
    @user_feedbacks = Feedback.all
  end

  # GET /user_feedbacks/1 or /user_feedbacks/1.json
  def show
     @user_feedback = Feedback.find(params[:id])
  end

  # GET /user_feedbacks/new
  def new
    @user_feedback = Feedback.new
  end

  # GET /user_feedbacks/1/edit
  def edit
    @user_feedback = Feedback.find(params[:id])
  end

  # POST /user_feedbacks or /user_feedbacks.json
  def create
    @user_feedback = Feedback.new(user_feedback_params)
    byebug

    respond_to do |format|
      if @user_feedback.save
        format.html { redirect_to feedback_index_path, notice: "user feedback was successfully created." }
        format.json { render :index, status: :created, location: feedback_index_path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_feedbacks/1 or /user_feedbacks/1.json
  def update
    respond_to do |format|
      if @user_feedback.update(user_feedback_params)
        format.html { redirect_to feedback_index_path, notice: "user feedback was successfully updated." }
        format.json { render :index, status: :ok, location: feedback_index_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_feedbacks/1 or /user_feedbacks/1.json
  def destroy
    @user_feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedback_index_path, notice: "user feedback was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_feedback
      @user_feedback = Feedback.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_feedback_params
      locale_params = I18n.available_locales.map do |local|
      [:"name_#{Mobility.normalize_locale(local)}", :"email_#{Mobility.normalize_locale(local)}", :"role_#{Mobility.normalize_locale(local)}", :"feedback_#{Mobility.normalize_locale(local)}"]
      end.flatten
      byebug
      params.require(:feedback).permit(locale_params)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
    def all_locales
        I18n.available_locales
    end
end

app/views/feedback/_form.html.haml
= form_for feedback, :url => (feedback.id.present? ? feedback_path(feedback) : feedback_index_path) do |f|
  - if feedback.errors.any?
    #error_explanation
      %h2= t 'global.forms.messages.errors', count:feedback.errors.count
      %ul
        - feedback.errors.full_messages.each do |message|
          %li= message
          
  - all_locales.each do |locale|
    .field
      - name = "name_#{Mobility.normalize_locale(locale)}"
      = f.label name, class: 'label label-default' 
      = f.text_field name, class: 'form-control'
    .field
      - email = "email_#{Mobility.normalize_locale(locale)}"
      = f.label email, class: 'label label-default' 
      = f.text_field email, class: 'form-control'
    .field
      - role = "role_#{Mobility.normalize_locale(locale)}"
      = f.label role, class: 'label label-default' 
      = f.text_field role, class: 'form-control'
    .field
      - feedback = "feedback_#{Mobility.normalize_locale(locale)}"
      = f.label feedback, class: 'label label-default' 
      = f.text_area feedback, class: 'form-control'
    %hr/
  .actions
    = f.submit t 'global.forms.submit'

app/views/feedback/edit.html.haml
%h1 Editing Patient Feedback
= render 'form', patient_feedback: @patient_feedback
= link_to 'Show', patients_feedback_path(@patient_feedback)
|
= link_to 'Back', patients_feedback_path

app/views/feedback/index.html.haml
-# <br><br><br>
-# <p id="notice"><%= notice %></p>

.container
    %h1
        = t '.Feedback'
        
    %table.table
        %thead.thead-dark
            %tr
                %th{:scope=>"col"}
                    = t ".Name"
                %th{:scope=>"col"}
                    = t ".Email"
                %th{:scope=>"col"}
                    = t ".Role"
                %th{:scope=>"col"}
                    = t ".Feedback"
                %th{colspan: "3", scope: "col"}
                    = t ".action"
                

        %tbody>
            - @user_feedbacks.each do |feedback| 
                %tr
                    %td
                        = feedback.name
                    %td
                        = feedback.email
                    %td
                        = feedback.role
                    %td
                        = feedback.feedback
                    %td
                        = link_to t('.show'), feedback_path(feedback)
                    %td
                        = link_to t('.edit'), edit_feedback_path(feedback)
                    %td
                        = link_to t('.destroy'), feedback_path(feedback), method: :delete, data: { confirm: 'Are you sure?' }
                
    %br

    = link_to t('.new_feedback'), new_feedback_path 
    

app/views/feedback/new.html.haml
%br/
%br/
%br/
%h1= t '.title'
= render 'form', feedback: @user_feedback
= link_to  t('feedback.new.back'), feedback_index_path

app/views/feedback/show.html.haml
%br/
%br/
%br/
.container
  %p#notice= notice
  = l @user_feedback.created_at, format: :long
  %p
    %strong= t ".patient_name"
    = @user_feedback.name
  %p
    %strong= t ".patient_email"
    = @user_feedback.email
  %p
    %strong= t ".role"
    = @user_feedback.role
  %p
    %strong= t ".feedback"
    = @user_feedback.feedback
  = link_to t('.edit'), edit_feedback_path(@user_feedback)
  |
  = link_to t('.back'), feedback_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Intertionalization
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      .container-fluid
        %a.navbar-brand{:href => "#"} Navbar
        %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNav", "data-bs-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarNav.collapse.navbar-collapse
          %ul.navbar-nav.d-flex
            %li.nav-item
              -# %a.nav-link.active{"aria-current" => "page", :href => "#"} New Feedbacks
              = link_to 'New Feedback', new_feedback_path , {class: 'nav-link active'}
            %li.nav-item
              %a.nav-link{:href => "/en"} Eng
            %li.nav-item
              %a.nav-link{:href => "/ja"} JPA
           
    .container
      = yield